### PR TITLE
Feature/rosetta h

### PR DESCRIPTION
**Pull request by alvinkl**
Standardize some of H challenge and added some H challenge

### CODE REVIEW

**Review by timolawl — COMMENTED** [review]
> Hofstadter Figure-Figure seuqnces

Spelling of the title needs to be corrected.

The prompt for this challenge needs to be rewritten so that it is less confusing to the user. I suggest simply having the challenge seed be `function ffr (n)` and `function ffs (n)` (both present in the challengeSeed), and have the prompt (task) reflect this.  Of course, the answer will need to be readjusted as well. If the return is `R(n)`, then what needs to be returned is not an array that is of the form `R[n]` but a function `R(n)`.

> Hofstadter Q sequence

The MathJax syntax needs to be corrected so that the equation is displayed, as it currently returns without any transformation.

The task needs to be rewritten such that it doesn't ask specifically for the 1000th term (this is something that one of the unit tests tests for itself), but to ask the user for what is actually asked for -- the JavaScript implementation of the Hofstadter Q sequence.

Also, please remove everything under the optional extra credit section, as it is not relevant.

Hope that helps,
Tim

**Comment by alvinkl** [comment]
I've updated the code :D

**Comment by timolawl** [comment]
Hi Alvin,

There's still a few changes that haven't been made from my earlier review. Can you make those changes and resubmit?

Thanks

**Comment by alvinkl** [comment]
@timolawl 
I've updated the code, hope those changes are correct as you requested :D

**Comment by timolawl** [comment]
Looks good! Merged.

**Pull request merged**
