### PR TITLE
Porting problems from RosettaCode

### PR DESCRIPTION
**Pull request by NitronR**

### CODE REVIEW

**Comment by tpoikela** [comment]
I cannot get bin/js2json_challenges.js running. Is `gulp watch-dev` working for you?
I get `Syntax Error: Unterminated template`. Looks like it's pointing to Element-wise operation challenge.

**Comment by NitronR** [comment]
I use `npm run watch-dev` to start `watch-dev` and it does work.
I will check the Element-wise operation challenge.
When I made the pull request for the challenge, it didn't show any errors on `watch-dev` or in the unit testing.

**Comment by NitronR** [comment]
Earlier as in when I made the pull request for the challenge.

**Comment by NitronR** [comment]
I ran `watch-dev` again. It shows no error.
Then I used `git checkout` to update the challenge file and then ran `watch-dev` and got the same error as yours. At line 10 there were some unusual character that caused the syntax error.
I have resolved the error and have added the file to this pull request. Merge and check if it works for you.

**Pull request merged**
